package com.novelreader.app.presentation.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val md_theme_light_primary = Color(0xFF6D5E0F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF8E287)
val md_theme_light_onPrimaryContainer = Color(0xFF221B00)
val md_theme_light_secondary = Color(0xFF655E40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEDE2BB)
val md_theme_light_onSecondaryContainer = Color(0xFF201C04)
val md_theme_light_tertiary = Color(0xFF426647)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3ECC8)
val md_theme_light_onTertiaryContainer = Color(0xFF00210D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1C16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1C16)
val md_theme_light_surfaceVariant = Color(0xFFEAE1D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4639)
val md_theme_light_outline = Color(0xFF7D7667)
val md_theme_light_outlineVariant = Color(0xFFCEC5B4)
val md_theme_light_inverseSurface = Color(0xFF33302B)
val md_theme_light_inverseOnSurface = Color(0xFFF6F0E7)
val md_theme_light_inversePrimary = Color(0xFFDEC74C)

// Dark Theme - 护眼阅读模式
val md_theme_dark_primary = Color(0xFFDEC74C)
val md_theme_dark_onPrimary = Color(0xFF393000)
val md_theme_dark_primaryContainer = Color(0xFF524600)
val md_theme_dark_onPrimaryContainer = Color(0xFFF8E287)
val md_theme_dark_secondary = Color(0xFFD0C6A1)
val md_theme_dark_onSecondary = Color(0xFF363016)
val md_theme_dark_secondaryContainer = Color(0xFF4D472A)
val md_theme_dark_onSecondaryContainer = Color(0xFFEDE2BB)
val md_theme_dark_tertiary = Color(0xFFA8CFAC)
val md_theme_dark_onTertiary = Color(0xFF14371D)
val md_theme_dark_tertiaryContainer = Color(0xFF2C4E32)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3ECC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1C16)
val md_theme_dark_onBackground = Color(0xFFE8E1D4)
val md_theme_dark_surface = Color(0xFF1D1C16)
val md_theme_dark_onSurface = Color(0xFFE8E1D4)
val md_theme_dark_surfaceVariant = Color(0xFF4B4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC5B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_outlineVariant = Color(0xFF4B4639)
val md_theme_dark_inverseSurface = Color(0xFFE8E1D4)
val md_theme_dark_inverseOnSurface = Color(0xFF33302B)
val md_theme_dark_inversePrimary = Color(0xFF6D5E0F)

// Sepia (护眼黄) - 阅读器专用
val SepiaBackground = Color(0xFFF5ECD7)
val SepiaText = Color(0xFF5C4B32)
val SepiaAccent = Color(0xFF8B7355)
